[project]
name = "csi-vae-gumbel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "optuna>=4.7.0",
    "optuna-integration[pytorch-distributed]>=4.7.0",
    "pydantic-settings>=2.12.0",
    "rich>=14.3.1",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.0",
    "seaborn>=0.13.2",
    "tigramite>=5.2.10.1",
    "torch>=2.9.1",
    "torchmetrics>=1.8.2",
]

[dependency-groups]
dev = [
    "ruff>=0.14.13",
    "ipykernel>=7.1.0",
]

[project.scripts]
opt = "csi_vae_gumbel.main:opt"
test = "csi_vae_gumbel.main:test"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 120
target-version = "py314"

[tool.ruff.lint]
select = [
    "ALL", # include all the rules, including new ones
]
ignore = [
    "D100",    # Missing docstring in public module
    "D104",    # Missing docstring in public package
    "D105",    # Missing docstring in magic method
    "FBT001",  # Boolean-typed positional argument in function definition
    "FBT002",  # Boolean-typed keyword argument in function definition
    "FBT003",  # Boolean-typed variable annotation
    "D203",    # Incorrect blank line before class
    "D213",    # Multi line summary second line
    "PLR0913", # Too many arguments in function definition
    "TC001",
    "TC002",
    "TC003",
]
